[package]
name = "answer-aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
mongodb = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
chrono = "0.4.38"
bson = "2.10.0"
